#!/bin/bash
# Emacs daemon startup script
# Carlo Sciolla
# 27 Nov 2011

EMACS=/usr/bin/emacs
#INIT=/Applications/Source\ Distributions/emacs-starter-kit/init.el
INIT=~/.emacs.d/init.el

$EMACS --debug-init -q -l $INIT --daemon
