#!/bin/bash

GROWL=/Applications/7zX.app/Contents/Resources/growlnotify
mvn $*
if [ $? -gt 0 ]
then
    echo "Build failed!" | $GROWL "Maven" --name maven --image ~/scripts/resources/maven-growl-failure.jpg > /dev/null 2>&1
else
    echo "Build completed successfully." | $GROWL "Maven" --name maven --image ~/scripts/resources/maven-growl-success.jpg > /dev/null 2>&1
fi
