#!/usr/local/bin/python

from csv     import reader
from os      import listdir
from os.path import join

folder = "/Users/skuro/Dropbox/IFTTT/GCal"

def parse_header(parser):
    "Parses the headers of the CSV file"
    header = parser.next()
    return header

def combine(header, event):
    joined = {}
    for k, v in zip(header, event):
        joined[k] = v
    print "Got "
    print joined
    return joined

def event2org(event):
    "unimplemented"

def store(org):
    "unimplemented"

def process_event(header, event):
    "Deals with a single event from the Google calendar"
    event = combine(header, event)
    org = event2org(event)
    store(org)

def process_events(header, parser):
    "Deals with all the events coming from Google calendar"
    for event in parser:
        process_event(header, event)

def process(update):
    "Deals with a file coming from the Google calendar IFTTT rule"
    with open(update) as csvfile:
        parser = reader(csvfile)
        header = parse_header(parser)
        process_events(header, parser)

updates = listdir(folder)
for update in updates:
    process(join(folder, update))
