#!/bin/sh

# Uses the currently installed jetty-runner jar from your local M2 repository
# to run a war file from the filesystem

# TODO: make use of some command line args
GROUP=org.mortbay.jetty
ARTIFACT=jetty-runner
VERSION=8.0.1.v20110908
REPO=~/.m2/repository
JETTY_RUNNER=$REPO/${GROUP//.//}/$ARTIFACT/$VERSION/$ARTIFACT-$VERSION.jar

if [ ! -f $FILE ]
then
  mvn dependency:get -DartifactId=$ARTIFACT -DgroupId=$GROUP -Dversion=$VERSION -DrepoUrl=http://repo1.maven.org/maven2
fi

java -jar $JETTY_RUNNER $@
