#!/bin/bash
#===============================================================================
#
#        FILE: xget
#
#       USAGE: xget URI [..args...]
#
# DESCRIPTION: Downloads and pretty prints XMLs from various sources (file,
#              HTTP, ...)
#
#     OPTIONS: see the 'usage' function below
#      AUTHOR: Carlo Sciolla <skuro@skuro.tk>
#     VERSION: 0.1
#
# Release notes:
#
# v0.1: Initial implementation based on curl, cat, GNU source-highlight and less
#
#===============================================================================

#===  FUNCTION  ================================================================
#        NAME: usage
# DESCRIPTION: prints out the instructions on how to use the program
#===============================================================================
function usage(){
    echo "$0 xml_resource [..args..]"
    echo
    echo "Retrieves the xml_resource and prints it on screen after running it through a beautifier."
    echo "If arguments are provided after the resource, they will be passed to the program used to fetch the resource."
    echo
    echo "Supported resources:"
    echo -e "\thttp://.....\t-> curl is used to retrieve"
    echo -e "\t/path/to/file\t-> cat is used to retrieve"
    echo
}

#-------------------------------------------------------------------------------
# checks whether the command invocation is valid. if not, print usage and exit
#-------------------------------------------------------------------------------
if [ $# -lt 1 ]
then
    usage
    exit $ERR_NOARG
fi

#-------------------------------------------------------------------------------
# Input arguments
#-------------------------------------------------------------------------------
RESOURCE="$1"   # the XML to retrieve
shift
EXTRA_ARGS="$@" # the arguments to provide to the retriever

RETRIEVER="curl"
PAGER="$PAGER"
HIGHLIGHTER="source-highlight -o STDOUT -s xml -f esc"
LINTER="xmllint --format -"

#-------------------------------------------------------------------------------
# Error codes
#-------------------------------------------------------------------------------
ERR_NOARGS=-10 # no arguments provided
ERR_BADURI=-20 # unsupported resource URI

#===  FUNCTION  ================================================================
#        NAME: choose-retriever
# DESCRIPTION: sets the value of $RETRIEVER based on the URI of the resource to
#              fetch
# PARAMETER 1: the URI of the resource to fetch
#===============================================================================
function choose-retriever(){
    if [[ "$1" =~ http* ]]
    then
        RETRIEVER="curl"
    elif [ -f "$1" ]
    then
        RETRIEVER="cat"
    else
        exit $ERR_BADURI
    fi
}

#===  FUNCTION  ================================================================
#        NAME: retrieve
# DESCRIPTION: use $RETRIEVER to grab a resource, passing the $EXTRA_ARGS if
#              provided. Then the resource is passed through the $LINTER, the
#              $HIGHLIGHTER and printed out via the $PAGER
#===============================================================================
function retrieve(){
    $RETRIEVER $EXTRA_ARGS $RESOURCE | $LINTER | $HIGHLIGHTER | $PAGER
}

#-------------------------------------------------------------------------------
# Run the retrieval process
#-------------------------------------------------------------------------------
choose-retriever "$RESOURCE"
retrieve
