#!/usr/bin/env python

"""XML escaping made easy"""

from xml.sax.saxutils import escape
import sys

def prin(x):
    print x + "\n"

if len(sys.argv) < 2:
    prin (escape(sys.stdin.read()))
else:
    map (prin, map(escape, sys.argv[1:]))
